### ISSUE TITLE
Javadoc for namespace default methods

### ISSUE THREAD

**Issue by gab1one** [imagej/imagej-ops#188] opened 2015-08-31 08:56 UTC
There should be javadoc for all the default methods in the namespaces.
Variable names do not always carry enough information, making some ops cryptic to use.
It is especially hard to tell if an argument can be safely set ``null`` or not .

It might be possible auto generate the javadoc, if all the parameters in the ops are annotated with the correct javadoc.

**Comment by ctrueden** [comment] 2016-01-21 23:25
Duplicate of #206.

**Closed by ctrueden** 2016-01-21 23:25 UTC
