### ISSUE TITLE
Add: Convolver using SymmetricSeparableConvolution of imglib2-algorithm

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#97] opened 2015-01-20 22:28 UTC
there is a [very nice implementation](https://github.com/imglib/imglib2-algorithm/blob/imglib2-algorithm-0.2.0/src/main/java/net/imglib2/algorithm/gauss3/SeparableSymmetricConvolution.java) of @tpietzsch for convolving images with certain types of kernels. We may want to add a Convolver for that (`Contigent` interface should be used to determine if kernel is separable. Additionally, there should be a (replaceable) heuristic to determine when to do FFT and when to use naive or separable convolution.

**Comment by ctrueden** [comment] 2015-01-27 21:46
@bnorthan Is this a project that interests you?

**Comment by ctrueden** [comment] 2015-01-27 22:02
Actually, this is a duplicate of (part of) #70.

**Closed by ctrueden** 2015-01-27 22:02 UTC
