### ISSUE TITLE
Cloned Repository Is Missing Imports

### ISSUE THREAD

**Issue by Nicholas-Schaub** [imagej/imagej-ops#534] opened 2017-12-14 14:20 UTC
I tried cloning the repository in Eclipse. I cleaned the project and updated Maven. There were errors in multiple packages. Opening a few of the packages revealed that there was an issue locating `net.imagej.ops.Ops`. Am I missing something or is this an error? Should this actually be a reference to the `net.imagej.ops.Op` interface?

**Comment by stelfrich** [comment] 2017-12-14 14:29
> Am I missing something or is this an error?

`net.imagej.ops.Ops.java` is automatically generated. Could you try to trigger the `generate-sources` phase manually by right-clicking on the project and _Run As > Maven generate-sources_?

**Comment by Nicholas-Schaub** [comment] 2017-12-14 14:39
I tried using `generate-sources` and got the following error:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ImageJ Ops 0.39.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-rules) @ imagej-ops ---
[INFO] 
[INFO] --- build-helper-maven-plugin:1.12:regex-property (sanitize-version) @ imagej-ops ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ imagej-ops ---
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify HEAD"
[INFO] Working directory: C:\Users\Nick Schaub\git\imagej-ops
[WARNING] Cannot get the revision information from the scm repository, proceeding with revision of UNKNOWN : 
Exception while executing SCM command.
[INFO] Storing buildNumber: UNKNOWN at timestamp: 1513262188501
[WARNING] Cannot get the branch information from the git repository: 
Error while executing command.
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify HEAD"
[INFO] Working directory: C:\Users\Nick Schaub\git\imagej-ops
[WARNING] Cannot get the branch information from the scm repository, proceeding with UNKNOWN_BRANCH : 
Exception while executing SCM command.
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO] 
[INFO] --- scijava-maven-plugin:1.0.0:set-rootdir (set-rootdir) @ imagej-ops ---
[INFO] Setting rootdir: C:\Users\Nick Schaub\git\imagej-ops
[INFO] 
[INFO] --- build-helper-maven-plugin:1.12:add-source (add-source) @ imagej-ops ---
[INFO] Source directory: C:\Users\Nick Schaub\git\imagej-ops\target\generated-sources\from-template added.
[INFO] 
[INFO] --- groovy-maven-plugin:1.5:execute (generate-sources) @ imagej-ops ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.580 s
[INFO] Finished at: 2017-12-14T09:36:29-05:00
[INFO] Final Memory: 35M/642M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:groovy-maven-plugin:1.5:execute (generate-sources) on project imagej-ops: Execution generate-sources of goal org.codehaus.mojo:groovy-maven-plugin:1.5:execute failed: A required class was missing while executing org.codehaus.mojo:groovy-maven-plugin:1.5:execute: org/apache/tools/ant/DemuxInputStream
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:groovy-maven-plugin:1.5
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/codehaus/mojo/groovy-maven-plugin/1.5/groovy-maven-plugin-1.5.jar
[ERROR] urls[1] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/velocity/velocity/1.7/velocity-1.7.jar
[ERROR] urls[2] = file:/C:/Users/Nick%20Schaub/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
[ERROR] urls[3] = file:/C:/Users/Nick%20Schaub/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[4] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/codehaus/gmaven/gmaven-plugin/1.5/gmaven-plugin-1.5.jar
[ERROR] urls[5] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/codehaus/gmaven/runtime/gmaven-runtime-api/1.5/gmaven-runtime-api-1.5.jar
[ERROR] urls[6] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/codehaus/gmaven/feature/gmaven-feature-api/1.5/gmaven-feature-api-1.5.jar
[ERROR] urls[7] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/codehaus/gmaven/runtime/gmaven-runtime-loader/1.5/gmaven-runtime-loader-1.5.jar
[ERROR] urls[8] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/codehaus/gmaven/feature/gmaven-feature-support/1.5/gmaven-feature-support-1.5.jar
[ERROR] urls[9] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/codehaus/gmaven/runtime/gmaven-runtime-support/1.5/gmaven-runtime-support-1.5.jar
[ERROR] urls[10] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/sonatype/gshell/gshell-io/2.4/gshell-io-2.4.jar
[ERROR] urls[11] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
[ERROR] urls[12] = file:/C:/Users/Nick%20Schaub/.m2/repository/com/thoughtworks/qdox/qdox/1.12/qdox-1.12.jar
[ERROR] urls[13] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/maven/shared/file-management/1.2.1/file-management-1.2.1.jar
[ERROR] urls[14] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/maven/shared/maven-shared-io/1.1/maven-shared-io-1.1.jar
[ERROR] urls[15] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar
[ERROR] urls[16] = file:/C:/Users/Nick%20Schaub/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar
[ERROR] urls[17] = file:/C:/Users/Nick%20Schaub/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar
[ERROR] urls[18] = file:/C:/Users/Nick%20Schaub/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar
[ERROR] urls[19] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/maven/reporting/maven-reporting-impl/2.0.4.1/maven-reporting-impl-2.0.4.1.jar
[ERROR] urls[20] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.1/plexus-interpolation-1.1.jar
[ERROR] urls[21] = file:/C:/Users/Nick%20Schaub/.m2/repository/commons-validator/commons-validator/1.2.0/commons-validator-1.2.0.jar
[ERROR] urls[22] = file:/C:/Users/Nick%20Schaub/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar
[ERROR] urls[23] = file:/C:/Users/Nick%20Schaub/.m2/repository/commons-digester/commons-digester/1.6/commons-digester-1.6.jar
[ERROR] urls[24] = file:/C:/Users/Nick%20Schaub/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar
[ERROR] urls[25] = file:/C:/Users/Nick%20Schaub/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
[ERROR] urls[26] = file:/C:/Users/Nick%20Schaub/.m2/repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
[ERROR] urls[27] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/maven/doxia/doxia-core/1.0-alpha-10/doxia-core-1.0-alpha-10.jar
[ERROR] urls[28] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-10/doxia-sink-api-1.0-alpha-10.jar
[ERROR] urls[29] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.0.4/maven-reporting-api-2.0.4.jar
[ERROR] urls[30] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/maven/doxia/doxia-site-renderer/1.0-alpha-10/doxia-site-renderer-1.0-alpha-10.jar
[ERROR] urls[31] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar
[ERROR] urls[32] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/codehaus/plexus/plexus-velocity/1.1.7/plexus-velocity-1.1.7.jar
[ERROR] urls[33] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/maven/doxia/doxia-decoration-model/1.0-alpha-10/doxia-decoration-model-1.0-alpha-10.jar
[ERROR] urls[34] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0-alpha-10/doxia-module-apt-1.0-alpha-10.jar
[ERROR] urls[35] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0-alpha-10/doxia-module-fml-1.0-alpha-10.jar
[ERROR] urls[36] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0-alpha-10/doxia-module-xdoc-1.0-alpha-10.jar
[ERROR] urls[37] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0-alpha-10/doxia-module-xhtml-1.0-alpha-10.jar
[ERROR] urls[38] = file:/C:/Users/Nick%20Schaub/.m2/repository/org/sonatype/gossip/gossip/1.2/gossip-1.2.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>net.imagej:imagej-ops:0.39.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.apache.tools.ant.DemuxInputStream
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```

**Comment by stelfrich** [comment] 2017-12-15 09:20
> I tried cloning the repository in Eclipse.

Which OS and which Eclipse version have you tried? Also, how exactly did you clone the repository? I was successful on Windows 10 with Eclipse Oxygen by first importing from Git and cancelling the import after the repository had been cloned. Subsequently, I could successfully import from an "existing Maven repository" pointing it at `<userfolder>/git/imagej-ops`.

**Comment by Nicholas-Schaub** [comment] 2017-12-15 21:24
I was running Windows 10 and Eclipse Oxygen.

I did continue with the import after the repository was cloned, so I'll try import form an existing maven repository and see if that does the trick. I'll report back.

**Comment by ctrueden** [comment] 2017-12-18 20:01
In my experience, Oxygen has new bugs surrounding M2E (the Eclipse/Maven integration). If you can use Neon, it would probably be better. Alternately, if you first run `mvn clean install` from the CLI, and then go back to Eclipse and rebuild the project (right-click the project, Maven, Update Project...), it will probably work.

**Comment by stelfrich** [comment] 2017-12-20 12:17
> I'll report back.

Any news, @Nicholas-Schaub? Did it work out for you?

**Comment by Nicholas-Schaub** [comment] 2017-12-23 17:14
@stelfrich Not yet. I got hung up with a couple other projects. I will be trying it out in the next couple of days. I'm going to try what ctreuden recommended with Oxygen, and then also try it in Neon as well. I run Neon on a couple machines and Oxygen on my newer machines, so it's not that big of a hassle. Sorry for the delay. I appreciate your quick responses.

**Comment by stelfrich** [comment] 2018-03-02 06:23
I am closing this issue for now, @Nicholas-Schaub. If you find time / new insights, feel free to re-open it!

**Closed by stelfrich** 2018-03-02 06:23 UTC

**Comment by ctrueden** [comment] 2018-03-02 19:51
@Nicholas-Schaub One other possibility is a corrupted local repository cache. The class `org.apache.tools.ant.DemuxInputStream` not being found implies that perhaps one of the JAR files on your classpath is corrupt. You could try wiping out `~/.m2/repository/ant` and `~/.m2/repository/org/apache/ant`, then doing `mvn -U clean install` from the CLI. If you haven't tried `mvn` on the command line yet, that is always a good thing to try, to narrow down whether the problem is specifically with Eclipse.
