### ISSUE TITLE
Clarify OpMethods

### ISSUE THREAD

**Issue by Squareys** [imagej/imagej-ops#176] opened 2015-08-03 12:08 UTC
Hello everybody!

I'd like to clarify how OpMethods in `Namespace` implementations and `OpService` should look like. Consider a common op hierarchy for a statistical max op:
 - `Op.Stat.Max`
 - `MaxOp`
 - `DefaultMax`

Two variants for its OpMethods are possible.
 - first:
```
@OpMethod(op = net.imagej.ops.stat.max.DefaultMaxFilter.class)
public <T extends RealType<T>> T max(final T out, final Iterable<T> input)
{
	final T result =
		(T) ops().run(net.imagej.ops.stat.max.DefaultMax.class, out, input);
	return result;
}
```
 - second:
```
@OpMethod(op = net.imagej.ops.stat.max.DefaultMaxFilter.class)
public <T extends RealType<T>> T max(final T out, final Iterable<T> input)
{
	final T result = (T) ops().run(Ops.Stat.Max.class, out, input);
	//                           ! ^^^^^^^^^^^^
	return result;
}
```

In my opinion, the second version is the "correct" one. That is because the first one prevents Ops from choosing the best option (which is one of its big features after all). A more optimized version for a compatible set of parameters could be never be chosen.

The second one allows this, though. Both are accepted by the NamespaceTest, but if missing, the test will suggest the first one.

Is my thinking correct, or did I miss something?

Greetings, Squareys.

**Comment by ctrueden** [comment] 2015-08-03 20:55
Firstly, I assume your reference to a `DefaultMaxFinder` is a typo, and should be `DefaultMax`. Correct?

When there is no clash between multiple op implementations, the current pattern is:
```java
@OpMethod(op = net.imagej.ops.stat.max.DefaultMax.class)
public <T extends RealType<T>> T max(final T out, final Iterable<T> input)
{
    final T result =
        (T) ops().run(net.imagej.ops.stat.max.DefaultMax.class, out, input);
    return result;
}
```
In other words: as specific as possible. This ensures you get exactly the expected op when calling its associated built-in method signature.

If multiple ops clash, the current rule of thumb is to choose the "most specific common type" of all involved ops in the clash. Sometimes this ends up being the `Ops.Foo.Bar` interface, but often times there is something more specific.

The thinking was to "lock down" the built-in op signatures as much as possible, since each one typically corresponds to one concrete implementation.

However, I am open to a change of thinking, if others believe that using the `Ops.Foo.Bar` interfaces across the board would be somehow superior. Certainly it would make the behavior of the built-ins much more extensible, which is always a two-edged sword.

**Comment by Squareys** [comment] 2015-08-03 22:03
> Firstly, I assume your reference to a DefaultMaxFinder is a typo, and should be DefaultMax. Correct?

Sorry, yes, this was partially copy-pasted and sketched without any compile checks and such.

> If multiple ops clash, the current rule of thumb is to choose the "most specific common type" of all involved ops in the clash.

That actually would still let Ops choose the op with highest priority/best fit for parameters, right? So my inital concern is false, if I understood correct:

For example, if we had `BetterMax` which is optimized for a ArrayList parameter (whatever), we would need to write:
```
@OpMethod(ops = {net.imagej.ops.stat.max.DefaultMax.class,
    net.imagej.ops.stat.max.BetterMax.class})
public <T extends RealType<T>> T max(final T out, final Iterable<T> input)
{
    final T result =
        (T) ops().run(net.imagej.ops.stat.max.MaxOp.class, out, input);
    return result;
}
```
since MaxOp ist the "most specific common type". This method would still retain the flexibility to choose BetterMax, if input is an ArrayList.

> Certainly it would make the behavior of the built-ins much more extensible

Indeed it would, and it would also be easier to work with as an imagej-ops developer (except if we had the methods autogenerated, which would be even easier ;) ).
A user could break alot of code with a broken implementation of SumOp for example (which would probably happen anyway, since most depending Ops get it via the `OpService.op()` method (?) ), but what else did you have in mind concerning "two-edged sword"?

**Comment by ctrueden** [comment] 2015-08-11 22:30
So, for consistency and elegance, I actually really like always typing on the toplevel op interface itself; e.g.:
```java
@OpMethod(ops = {net.imagej.ops.stats.max.DefaultMax.class,
    net.imagej.ops.stats.max.BetterMax.class})
public <T extends RealType<T>> T max(final T out, final Iterable<T> input)
{
    final T result =
        (T) ops().run(net.imagej.ops.Ops.Stats.Max.class, out, input);
    return result;
}
```

This would provide maximum extensibility, but also maximum fragility to the built-in methods. That's what I meant by "two-edged sword": it _will_ happen in the future that at some point, a built-in method signature stops working completely due to the addition of an (on the surface unrelated) new op implementation for the same op name.

So the question is: what do we value more?

A. The built-in methods continuing to work whenever possible, even in the face of a potentially broken global state; or
B. The built-in methods being as extensible as possible, such that developers can redefine what it means to execute e.g. `max(T, Iterable<T>)`
?

**Comment by ctrueden** [comment] 2015-12-21 17:26
I still do not have a super confident answer to the dilemma of type-safety vs. extensibility posed above. And would still value the feedback of others on their preference.

However, I just want to refine my proposal in one sense, according to my current thinking:

If we go with the "built-methods are as type-safe as possible" approach, it might be good to eliminate the middleman and just call each op directly somehow. Or at least: skip the matching step in favor of instantiating exactly the specified op.

**Comment by ctrueden** [comment] 2016-01-21 23:32
So, now we have verbal feedback from @dietzc and @stelfrich and @hinerm, and all agree that we want to favor extensibility, i.e. option 2 above. I will ask @LeonYang5114 to change over all the built-ins this way.

**Comment by ctrueden** [comment] 2016-01-21 23:33
@dietzc says: "Remove unnecessary superfluous duplicate redundant method signatures, especially in the math namespace!"

**Comment by LeonYang5114** [comment] 2016-01-22 00:19
@ctrueden I think I need to talk with you in more details to know what exactly you want.

**Comment by ctrueden** [comment] 2016-01-22 00:25
@LeonYang5114 Certainly, that is the plan: we will chat about this when I am back in the office. I will explain then.

**Comment by ctrueden** [comment] 2016-02-23 03:43
@LeonYang5114 made big progress in #348, which is now merged.

**Comment by stelfrich** [comment] 2016-02-23 13:55
Nice!

May I add another flavor to the discussion by dropping _reproducibility_? I still think about the namespace methods as a gateway from scripts. The more general implementation we had decided on might change behavior of user-written scripts in a way that is not completely transparent to user. This is along the lines your argumentation, @ctrueden, speaking of the "two-edged sword". Is there a way to improve that particular situation:

1. Write working script
2. Someone drops a new op implementation that is used by a namespace method that is used in the aforementioned script
3. Script stops working without any changes from my side

**Comment by dietzc** [comment] 2016-02-23 14:09
We can only test this on core level. If someone plugs-in any arbitrary `Op` with his personal `jar`, this might happen, yes. However, on core-level we can do it with what I called `consistency-tests`. See: https://github.com/imagej/imagej-ops/issues/192. Is this what you meant?

**Comment by stelfrich** [comment] 2016-02-23 14:22
> Is this what you meant?

Yes (although I am curious about the implementation, since it requires a default implementation we test against, right?). Those are supposed to be unit tests?

**Comment by dietzc** [comment] 2016-02-23 14:41
> Yes (although I am curious about the implementation, since it requires a default implementation we test against, right?). Those are supposed to be unit tests?

For consistency you actually don't need a default implementation, because you only have to check that all `Op`s produce the same result. The functionality of the `Op`s should for example be tested in the first `Op`.

**Comment by ctrueden** [comment] 2016-04-27 18:51
We have thoroughly settled on using the general op interfaces for the built-in signatures. And #348 goes most of the way toward achieving it in reality. So I am going to close this issue as resolved!

Regarding reproducibility: you can open a separate issue for that if you want @stelfrich. Although I will warn that with all the seams in ImageJ2, and ImageJ Ops in particular, universal reproducibility because extremely tricky. The best we can do is say "this script will give the same answer if you run ImageJ 2.3.1 without any extensions because that's what I used." I mean, in principle, I agree that later versions of ImageJ should not alter the result, and as @dietzc says, we will do lots of regression tests to try and prevent that. But if someone adds ops to the system which do not conform to the ops social contract (that all ops with the same name and arguments need to give the same result deterministically), then all bets are off.

See also #192. We could _maybe_ do some runtime testing of ImageJ when extensions are present, but that comes rife with challenges of course.

**Closed by ctrueden** 2016-04-27 18:51 UTC
Labels: question
