### ISSUE TITLE
Reusing Ops

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-ops#164] opened 2015-07-18 18:51 UTC
Hi @ctrueden & @hinerm,

I just ran into a problem and I'm not sure if this is a bug or feature:

https://github.com/imagej/imagej-ops/commit/83130af9fe8ced034c23fd80cec4cc3a0465d39a

I want to reuse a create op via `ops().run(Op, obj)`. However, this doesn't work and the following error is thrown:

```
java.lang.IllegalStateException: Context already injected: net.imagej.ops.create.img.CreateImgFromImg#ops
	at org.scijava.Context.inject(Context.java:430)
	at org.scijava.Context.inject(Context.java:372)
	at net.imagej.ops.DefaultOpService.module(DefaultOpService.java:145)
	at net.imagej.ops.DefaultOpService.run(DefaultOpService.java:111)
	at net.imagej.ops.ReuseOpTest.reuseOpTest(ReuseOpTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
Bug or feature?

**Comment by hinerm** [comment] 2015-07-20 15:04
I vote bug. I feel like `DefaultOpService` should only inject a `Context` if it is creating an `Op`.

@ctrueden is there ever a case where [this line](https://github.com/imagej/imagej-ops/blob/imagej-ops-0.15.0/src/main/java/net/imagej/ops/DefaultOpService.java#L168) would be necessary?

**Comment by ctrueden** [comment] 2015-07-20 15:07
I am incline to call this a bug as well. But we should think a bit carefully here, and then ensure we have a regression test in place to verify the context injection behavior is what we want in various cases.

@hinerm Did you try commenting out that line? Do all the tests still pass? My current feeling (without testing) is that without that line, there are cases where newly create `Op`s won't be injected at all, and things will fail. But I could certainly be wrong.

**Comment by hinerm** [comment] 2015-07-20 17:00
@ctrueden If you comment out that line tests still pass. However they do so slightly artificially because the [`module` test](https://github.com/imagej/imagej-ops/blob/imagej-ops-0.15.0/src/test/java/net/imagej/ops/OpServiceTest.java#L146) uses an op that doesn't have any `@Parameters`.. so it doesn't matter if it's injected or not. And in fact, if an object doesn't have any parameters, it can be "injected" ad nauseam.

I started [a branch](https://github.com/imagej/imagej-ops/blob/imagej-ops-0.15.0/src/test/java/net/imagej/ops/OpServiceTest.java#L146) to cover these scenarios. I ran into problems because, given that you can inject arbitrary objects, there is no API to use to determine if something has been injected or not previously.

We could `try..catch` but that feels clunky doesn't it..? Why don't we change injection so that if a context does encounter a field that has already been injected, it only throws an exception if the value is from a different context?

**Comment by ctrueden** [comment] 2015-07-20 18:40
> Why don't we change injection so that if a context does encounter a field that has already been injected, it only throws an exception if the value is from a different context?

I was reluctant to do that until now, because it felt to me like attempting double injection is generally a logic error. And code should be changed not to inject in inappropriate cases, since injection is a rather expensive operation.

But perhaps that is not a good enough justification for disallowing it in every case...

**Comment by ctrueden** [comment] 2015-09-16 15:35
@dietzc Is this still an issue?

**Comment by dietzc** [comment] 2015-09-16 15:46
no :+1:

**Comment by ctrueden** [comment] 2015-09-16 18:10
OK cool. Closing.

**Closed by ctrueden** 2015-09-16 18:10 UTC
