### ISSUE TITLE
Op expression parser

### ISSUE THREAD

**Issue by iarganda** [imagej/imagej-ops#100] opened 2015-01-24 21:26 UTC
```
ops.expr("sqrt(dx*dx + dy*dy + dxy*dxy)", {"dx" => dx, "dy" => dy, "dxy" => dxy});
```
Which means:
```
ops.run("sqrt", ops.add(ops.add(ops.multiply(dx, dx), ops.multiply(dy, dy)), ops.multiply(dxy, dxy)));
```

**Comment by LeeKamentsky** [comment] 2015-01-25 06:48
Holey moley - nice, nice nice. It's starting to look Pythonic.

**Comment by ctrueden** [comment] 2015-01-25 17:03
@LeeKamentsky Heh, we have a ways to go yet. The issue is still open, after all!

**Comment by ctrueden** [comment] 2015-01-27 21:34
Closing in favor of #105.

**Closed by ctrueden** 2015-01-27 21:34 UTC
